name: Auto Release APK

on:
  schedule:
#    - cron: "0 12 * * 5"
    - cron: "*/5 * * * *"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # get version number
      - name: Get Version
        id: version
        run: echo "version=$(echo | cat ./version)" >> $GITHUB_ENV
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      # rename apk file
      - name: Rename APK File
        run: bash mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/mIPIV_${{ env.version }}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/mIPIV_${{ env.version }}.apk
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ env.version }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/mIPIV_${{ env.version }}.apk
          asset_name: mIPIV_${{ env.version }}.apk
          asset_content_type: application/zip
      # increase version number
      - name: Increment Version
        run: bash sed -ri 's/(.*)([0-9])(\.)([0-9])([0-9])/echo "\1\2\3\4((\5+1))"/ge' ./version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
